"""empty message

Revision ID: 0f7a4db71773
Revises: 609bc71969e1
Create Date: 2021-07-27 10:58:29.452715

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f7a4db71773'
down_revision = '609bc71969e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('table_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('team', sa.String(), nullable=False),
    sa.Column('point', sa.Integer(), nullable=False),
    sa.Column('match', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('table_scores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('team1', sa.String(), nullable=False),
    sa.Column('team2', sa.String(), nullable=False),
    sa.Column('score', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('players',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('table_result_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['table_result_id'], ['table_results.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('players')
    op.drop_table('table_scores')
    op.drop_table('table_results')
    # ### end Alembic commands ###
