"""empty message

Revision ID: 44502f6c2aea
Revises: b38f1fc42b38
Create Date: 2021-08-12 18:59:52.781052

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '44502f6c2aea'
down_revision = 'b38f1fc42b38'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users_opponents', sa.Column('date', sa.String(length=50), nullable=True))
    op.add_column('users_opponents', sa.Column('phone', sa.String(length=50), nullable=True))
    op.alter_column('users_opponents', 'city',
               existing_type=sa.VARCHAR(length=33),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users_opponents', 'city',
               existing_type=sa.VARCHAR(length=33),
               nullable=False)
    op.drop_column('users_opponents', 'phone')
    op.drop_column('users_opponents', 'date')
    # ### end Alembic commands ###
