"""empty message

Revision ID: 4f58e60e2886
Revises: 039d513471c2
Create Date: 2021-09-25 11:12:56.386680

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f58e60e2886'
down_revision = '039d513471c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('queues_opponents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('queue_name', sa.String(length=50), nullable=True),
    sa.Column('queue_email', sa.String(length=50), nullable=True),
    sa.Column('queue_phone', sa.String(length=50), nullable=True),
    sa.Column('queue_category', sa.String(length=50), nullable=True),
    sa.Column('queue_city', sa.String(length=50), nullable=True),
    sa.Column('queue_district', sa.String(length=50), nullable=True),
    sa.Column('queue_date', sa.String(length=50), nullable=True),
    sa.Column('queue_accept', sa.Boolean(), nullable=True),
    sa.Column('queue_message', sa.Text(), nullable=True),
    sa.Column('queue_user_opponent_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['queue_user_opponent_id'], ['offers_opponents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('queues_opponents')
    # ### end Alembic commands ###
