"""empty message

Revision ID: 4fa973774e5f
Revises: fe76e1d34a19
Create Date: 2021-07-31 19:09:49.463702

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4fa973774e5f'
down_revision = 'fe76e1d34a19'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('roles_admin_users')
    op.drop_table('role_admin')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('role_admin',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('role_admin_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=40), autoincrement=False, nullable=True),
    sa.Column('description', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='role_admin_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('roles_admin_users',
    sa.Column('admin_login_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('role_admin_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['admin_login_id'], ['admin_login.id'], name='roles_admin_users_admin_login_id_fkey'),
    sa.ForeignKeyConstraint(['role_admin_id'], ['role_admin.id'], name='roles_admin_users_role_admin_id_fkey')
    )
    # ### end Alembic commands ###
