"""empty message

Revision ID: 5e42d88f7f75
Revises: 14f01a7eb67f
Create Date: 2021-12-18 11:39:58.936731

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e42d88f7f75'
down_revision = '14f01a7eb67f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('members', sa.Column('tour_member_name', sa.String(length=50), nullable=True))
    op.add_column('members', sa.Column('tour_member_phone', sa.String(length=50), nullable=True))
    op.add_column('members', sa.Column('tour_member_email', sa.String(length=50), nullable=True))
    op.add_column('members', sa.Column('tour_member_accept', sa.Boolean(), nullable=True))
    op.drop_column('members', 'member_phone')
    op.drop_column('members', 'member_accept')
    op.drop_column('members', 'member_name')
    op.drop_column('members', 'member_email')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('members', sa.Column('member_email', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('members', sa.Column('member_name', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('members', sa.Column('member_accept', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('members', sa.Column('member_phone', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.drop_column('members', 'tour_member_accept')
    op.drop_column('members', 'tour_member_email')
    op.drop_column('members', 'tour_member_phone')
    op.drop_column('members', 'tour_member_name')
    # ### end Alembic commands ###
