"""empty message

Revision ID: 609bc71969e1
Revises: 2392c7452d08
Create Date: 2021-07-26 22:49:43.623084

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '609bc71969e1'
down_revision = '2392c7452d08'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users_accounts', sa.Column('logout', sa.Boolean(), server_default='false', nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users_accounts', 'logout')
    # ### end Alembic commands ###
