"""empty message

Revision ID: 620106fef8ee
Revises: 07931d3c0569
Create Date: 2021-07-31 09:24:58.356981

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '620106fef8ee'
down_revision = '07931d3c0569'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admin_login', sa.Column('username', sa.String(length=33), nullable=False))
    op.add_column('admin_login', sa.Column('password', sa.String(length=255), nullable=False))
    op.add_column('admin_login', sa.Column('remember', sa.Boolean(), nullable=True))
    op.create_unique_constraint(None, 'admin_login', ['password'])
    op.create_unique_constraint(None, 'admin_login', ['username'])
    op.drop_column('admin_login', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admin_login', sa.Column('name', sa.VARCHAR(length=33), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'admin_login', type_='unique')
    op.drop_constraint(None, 'admin_login', type_='unique')
    op.drop_column('admin_login', 'remember')
    op.drop_column('admin_login', 'password')
    op.drop_column('admin_login', 'username')
    # ### end Alembic commands ###
