"""empty message

Revision ID: 705653741a7c
Revises: 7d5a2ca46fe4
Create Date: 2021-09-27 14:38:04.943388

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '705653741a7c'
down_revision = '7d5a2ca46fe4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users_accounts', sa.Column('count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users_accounts', 'count')
    # ### end Alembic commands ###
