"""empty message

Revision ID: 8eca6fecc702
Revises: a59a9ee9894c
Create Date: 2021-07-22 11:19:42.129207

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8eca6fecc702'
down_revision = 'a59a9ee9894c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products', 'price',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=33),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=33),
               nullable=True)
    op.alter_column('products', 'price',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
