"""empty message

Revision ID: 9a35e57ddeb0
Revises: 2f22fb7d3179
Create Date: 2021-07-22 13:52:49.279688

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a35e57ddeb0'
down_revision = '2f22fb7d3179'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('color', sa.String(), nullable=False))
    op.add_column('orders', sa.Column('size', sa.String(), nullable=False))
    op.add_column('orders', sa.Column('sex', sa.String(), nullable=False))
    op.add_column('orders', sa.Column('quantity', sa.Integer(), nullable=False))
    op.drop_constraint('orders_product_id_fkey', 'orders', type_='foreignkey')
    op.drop_column('orders', 'product_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('orders_product_id_fkey', 'orders', 'products', ['product_id'], ['id'])
    op.drop_column('orders', 'quantity')
    op.drop_column('orders', 'sex')
    op.drop_column('orders', 'size')
    op.drop_column('orders', 'color')
    # ### end Alembic commands ###
