"""empty message

Revision ID: 9f3017e13d27
Revises: 
Create Date: 2021-07-30 18:00:23.149708

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f3017e13d27'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users_accounts', sa.Column('active', sa.Boolean(), nullable=True))
    op.drop_column('users_accounts', 'logout')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users_accounts', sa.Column('logout', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True))
    op.drop_column('users_accounts', 'active')
    # ### end Alembic commands ###
