"""empty message

Revision ID: a524b0276282
Revises: fa49856d06f9
Create Date: 2021-07-22 11:29:11.717719

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a524b0276282'
down_revision = 'fa49856d06f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=33),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=33),
               nullable=True)
    # ### end Alembic commands ###
