"""empty message

Revision ID: a59a9ee9894c
Revises: 0dd5b91348e1
Create Date: 2021-07-22 11:13:06.794099

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a59a9ee9894c'
down_revision = '0dd5b91348e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products', 'price',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=33),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=33),
               nullable=True)
    op.alter_column('products', 'price',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
