"""empty message

Revision ID: bdec575de56d
Revises: 4fa973774e5f
Create Date: 2021-08-01 10:54:55.800520

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bdec575de56d'
down_revision = '4fa973774e5f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('admin_login')
    op.add_column('users_accounts', sa.Column('remember', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users_accounts', 'remember')
    op.create_table('admin_login',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('username', sa.VARCHAR(length=33), autoincrement=False, nullable=False),
    sa.Column('password', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('remember', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='admin_login_pkey'),
    sa.UniqueConstraint('password', name='admin_login_password_key'),
    sa.UniqueConstraint('username', name='admin_login_username_key')
    )
    # ### end Alembic commands ###
