"""add is_new column

Revision ID: d2a12c5ade80
Revises: 4e15ec89a073
Create Date: 2021-07-11 18:25:12.507465

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd2a12c5ade80'
down_revision = '4e15ec89a073'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('is_new', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'is_new')
    # ### end Alembic commands ###
