"""empty message

Revision ID: d5a8dfe7d39d
Revises: 620106fef8ee
Create Date: 2021-07-31 09:27:58.620019

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd5a8dfe7d39d'
down_revision = '620106fef8ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_login',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=33), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('remember', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('password'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('admin_login')
    # ### end Alembic commands ###
