"""empty message

Revision ID: f69837a77724
Revises: 4f58e60e2886
Create Date: 2021-09-25 11:19:38.681248

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f69837a77724'
down_revision = '4f58e60e2886'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('queues_opponents', sa.Column('queue_offer_opponent_id', sa.Integer(), nullable=True))
    op.drop_constraint('queues_opponents_queue_user_opponent_id_fkey', 'queues_opponents', type_='foreignkey')
    op.create_foreign_key(None, 'queues_opponents', 'offers_opponents', ['queue_offer_opponent_id'], ['id'])
    op.drop_column('queues_opponents', 'queue_user_opponent_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('queues_opponents', sa.Column('queue_user_opponent_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'queues_opponents', type_='foreignkey')
    op.create_foreign_key('queues_opponents_queue_user_opponent_id_fkey', 'queues_opponents', 'offers_opponents', ['queue_user_opponent_id'], ['id'])
    op.drop_column('queues_opponents', 'queue_offer_opponent_id')
    # ### end Alembic commands ###
