"""empty message

Revision ID: fa49856d06f9
Revises: 8eca6fecc702
Create Date: 2021-07-22 11:27:45.500381

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa49856d06f9'
down_revision = '8eca6fecc702'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products', 'price',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=33),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=33),
               nullable=True)
    op.alter_column('products', 'price',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
