"""empty message

Revision ID: fe76e1d34a19
Revises: d5a8dfe7d39d
Create Date: 2021-07-31 18:51:32.720287

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe76e1d34a19'
down_revision = 'd5a8dfe7d39d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('role_admin',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=40), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('roles_admin_users',
    sa.Column('admin_login_id', sa.Integer(), nullable=True),
    sa.Column('role_admin_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['admin_login_id'], ['admin_login.id'], ),
    sa.ForeignKeyConstraint(['role_admin_id'], ['role_admin.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('roles_admin_users')
    op.drop_table('role_admin')
    # ### end Alembic commands ###
